name: CMake
on: [push]

jobs:
  build_llvm:
    runs-on: ubuntu-latest
    env:
      LLVM_VERSION: "19.1.5"
    steps:    
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.0
      
      - name: Checkout LLVM
        run: git clone --depth 1 --branch llvmorg-${{ env.LLVM_VERSION }} https://github.com/llvm/llvm-project.git
        
      - name: Configure LLVM
        run: cmake -G Ninja -S llvm-project/llvm -B llvm-project/build -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="llvm;clang;lld"

      - name: Build LLVM
        run: cmake --build llvm-project/build --config Release

      - name: Install LLVM
        run: cmake --install llvm-project/build --prefix $GITHUB_WORKSPACE/llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-ubuntu-release
 
      - name: Zip LLVM
        run: tar -cvzf llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-ubuntu-release.tar.gz $GITHUB_WORKSPACE/llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-ubuntu-release
        
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LLVM
          path: llvm+clang+lld-${{ env.LLVM_VERSION }}-x86_64-ubuntu-release.tar.gz
          retention-days: 3

